# Generated by Django 4.0.6 on 2022-07-18 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eCom', '0002_item_brand_item_description_item_img_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('description', models.CharField(default='', max_length=500)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('numReviews', models.IntegerField(blank=True, default=0)),
                ('countInStock', models.IntegerField(blank=True, default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('img', models.TextField(default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
